---
# tasks file for chamilo-deploy

- name: for RH / CentOS
  include: rh_centos.yml
  when:
  - ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  - ansible_distribution_major_version == "7"

- name: for Debian / Ubuntu
  include: debian_ubuntu.yml
  when:
  - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
